### ISSUE TITLE
Immediate copy to clipboard

### ISSUE THREAD

**Issue by 1nternerd** [umahmood/ShareFile#2]
Do you think it would be useful to directly copy the link generated by transfer.sh to the clipboard?
I found myself marking the link over and over again and figured that it would improve my productivity when the link is copied directly.
I already have implemented this on a [fork of your project](https://github.com/1nternerd/ShareFile/tree/feature-copy-link-to-clipboard), so if you find the addition useful I would happily open a pull request. Also please feel free to improve my solution, i was just hacking some stuff together :)

**Comment by umahmood** [comment]
Hello, you should now find that the link is automatically copied to the clipboard. Thank you.

**Comment by motoom** [comment]
That was the first thing I noticed in the little animation on the github page... the manual marking with the mouse of the URL. I'm glad the name is placed automatically on the clipboard, this is 99% the use case.
