### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by srikat** [umahmood/ShareFile#5]
I installed the plugin from within fman using Ctrl+Shift+P in Windows.

With a file selected I invoked the command palette and selected the option to share a small zip file to test and it shows:

![screenshot](https://i.imgur.com/6Ow0eNB.png)

Any idea?

**Comment by umahmood** [comment]
Hello, 

The ShareFile plugin uploads files to https://transfer.sh/ and then returns the link. The error message suggessts that transfer.sh is closing the connection for some reason. I tried to upload a file via the website and I was getting a http 500 error. However, now it appears uploads are working, can you try again?

Note: I no longer have access to fman as I have moved to a different platform, so cannot test it myself.

Thanks.

**Comment by srikat** [comment]
Thanks. You are right. It is working now.

Just curious.. feel free not to reply: When you say moved to a different platform, are you referring to a OS or file manager?

**Comment by umahmood** [comment]
Great! nice to see it's working now.

Sorry, I should have been clearer. I have switched file managers, I have gone back to using Midnight Commander https://en.wikipedia.org/wiki/Midnight_Commander .

It is a terminal based file manager, and I spend all my time in the terminal so it fits better into my workflow. I also switch across OS's alot for work and MC is installed on all of them, so it is my main file manager.  

fman is still a great file manager :smile:
